name: ICTC_Website
description: "An internship project"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_survey:
    path: ./pubs/flutter_survey-0.1.4_scale
  cupertino_icons: ^1.0.2
  responsive_builder: ^0.7.0
  flutter_svg: ^2.0.9
  supabase_flutter: ^2.5.1
  email_validator: ^2.1.17
  json_annotation: ^4.8.1
  file_picker: ^8.0.0+1
  html_unescape: ^2.0.0
  dropdown_button2: ^2.3.9
  dropdown_search: ^5.0.6
  
  

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.0

flutter:
  fonts:
    - family: Montserrat
      fonts: 
      - asset: assets/fonts/Montserrat-Light.ttf
        weight: 300
      - asset: assets/fonts/Montserrat-Regular.ttf
        weight: 400
      - asset: assets/fonts/Montserrat-SemiBold.ttf
        weight: 500
      - asset: assets/fonts/Montserrat-Bold.ttf
        weight: 600
      - asset: assets/fonts/Montserrat-ExtraBold.ttf
        weight: 700
      - asset: assets/fonts/Montserrat-Black.ttf
        weight: 800
      
  assets:
    - assets/images/

  uses-material-design: true